TWITTER_CONSUMER_KEY = "T2XGPljTPrY3uYmwBV4ofpgji"
TWITTER_CONSUMER_SECRET = "B4MQSM0WC0US7tVQctQNWHNeSuxHFmKuzBVQSxRD9lBWGDSxi6"
TWITTER_ACCESS_TOKEN = "4923890262-4tBminwmZoKY5QMErBFEdMacDiKolOo65fN7Wge"
TWITTER_ACCESS_TOKEN_SECRET = "BrwD3lgxXi5cfsWpAFRtwCQd3tUWrk7QRyPTH3VxRtRp6"
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAKh7XAEAAAAA2I8fX%2BmLCp7Huh0KoL1pu9de3dU%3DlKZgQxIq0Rej7EadNQpqlKnhVMrDLMbgFbIgHGjmwwA67DhfJ7"

TWITTER_USERNAMES = [
    "traderstewie",
    "the_chart_life",
    "canuck2usa",
    "sunrisetrader",
    "tmltrader",
]
